### PR TITLE
Retry on EOF errors from HTTP client

### LINKED ISSUE #198: Requests to Okta are not retried on connection problems errors
Any connection problems are considered permanent and requests to Okta don't get retried by `okta-golang-sdk`. In my service's logs I see requests done by okta-golang-sdk fail from time to time with error:
```
Post "https://{redacted my custom org domain name}/api/v1/apps": EOF
```
and these requests don't get retried.

This is the problematic code block:
https://github.com/okta/okta-sdk-golang/blob/bb2e8ecf6ad832bfdfb8216fb3a653294e6274b5/okta/requestExecutor.go#L298-L301

I think the author's @bogdanprodan-okta  intention was to respect the configured request timeouts but as a side effect requests that fail immediately (<30ms) because of a broken connection aren't retried.

### PR DESCRIPTION
**Pull request by bogdanprodan-okta**
Fix #198

### CODE REVIEW

**Review by bretterer — COMMENTED** [review]
LGTM

**Review by bretterer — APPROVED** [review]

File: okta/requestExecutor.go [hunk 1]
```diff
@@ -295,7 +295,10 @@ func (re *RequestExecutor) doWithRetries(ctx context.Context, req *http.Request)
 	}
 	operation := func() error {
 		resp, err = re.httpClient.Do(req.WithContext(ctx))
-		if err != nil {
+		if err == io.EOF {
```
Comment (adw1n) [inline okta/requestExecutor.go:298]: @bogdanprodan-okta @bretterer please can you change it to `errors.Is(err, io.EOF)` and use `errors.Is` in the future? okta-golang-sdk lets users provide their own httpClient instance. This means users may choose to have a custom transport implementation which wraps the errors. E.g. they may wish to add stacktraces to every error using https://github.com/pkg/errors library. It's really not an uncommon use case. Please see this code:

```
package main

import (
	"fmt"
	"io"

	"github.com/pkg/errors"
)

func main() {
	err := errors.WithStack(io.EOF)
	fmt.Println(err == io.EOF)
	fmt.Println(errors.Is(err, io.EOF))
}
```

Output:
```
false
true
```
